Feature/header
YaroslavKnysh/team_project_13_37 pull request #22
Opened 2021-07-04 18:29 UTC by Ruslan-GH

2021-07-04 22:26 UTC, Glitch458 requested changes
Сверяем вопросы и добиваем

2021-07-04 22:26 UTC, Glitch458 commented on src/partials/header.html
> +            </div>
Вам с @Kryassan нужно будет согласовать общий стиль логотипа и потом дать ему общий для двоих класс "logo"

2021-07-04 22:26 UTC, Glitch458 commented on src/partials/header.html
> +        <nav class="navigation">
Логотип нужно тоже завернуть в навигацию

2021-07-04 22:26 UTC, Glitch458 commented on src/partials/header.html
> +            <svg class="mobile-menu__icon-menu" width="21" height="12">
ещё одна отдельная svg огонька?)

2021-07-04 22:26 UTC, Glitch458 commented on src/partials/header.html
> +                    <a class="navigation__link" href="#" target="blank" rel="noopener noreferrer">Studying program</a>
Нужно проверить все ссылки. Нужны ли тут `target="blank" rel="noopener noreferrer"` для внутренней навигации. И если уже писать 'terget' - то '_blank'

2021-07-04 22:26 UTC, Glitch458 commented on src/sass/components/_header.scss
> +  // font задані орієнтовно так, як в макеті відсутня інфо. Даний текст відображається як графічний елекмент.
на каком то макете эти стили есть. позже найдем

2021-07-04 22:26 UTC, Glitch458 commented on src/sass/components/_header.scss
> +.header__icon-menu {
не пойму откуда аутлайн?)

2021-07-04 22:26 UTC, Glitch458 commented on src/sass/components/_modal-window.scss
> +  outline: 1px solid red;
опять аутлайн

2021-07-04 22:26 UTC, Glitch458 commented on src/sass/components/_modal-window.scss
> +  outline: 1px solid blue;
наверное забыл поубирать)

2021-07-05 15:01 UTC, Glitch458 commented on src/partials/header.html
> +            </div>
Это на потом, щас оставляй как есть

2021-07-05 15:01 UTC, Glitch458 commented on src/partials/header.html
> +                    <a class="navigation__link" href="#" target="blank" rel="noopener noreferrer">Studying program</a>
Upd: с внутренней навигации убирай таргеты)

2021-07-05 19:26 UTC, Kryassan commented on src/partials/header.html
> +            </div>
учитывая, что Руслан идет раньше, то я возьму его классы

2021-07-05 21:39 UTC, Glitch458 approved these changes
Принимаю, с правками на потом

2021-07-05 21:39 UTC, Glitch458 commented on src/partials/header.html
>                      <a class="navigation__link" href="#" target="blank" rel="noopener noreferrer">Studying program</a>
тут ссылочку пропустил) И прости, забыл сказать, `rel` тоже не нужен) Но это исправление на потом

2021-07-05 22:05 UTC, merged