about-styles
YaroslavKnysh/team_project_13_37 pull request #40
Opened 2021-07-06 17:01 UTC by OleksandrKudriavtsev

Обратите внимание на .container при 1366рх. Ширина должна  быть меньше 1314рх (1205 по макету), потому, при задании конкретных ширин дивам справа один марджин дополняет другой (ошибка?).
Может особый контейнер себе создать на основе общего в своем SASS паршале и навесить себе?

2021-07-06 19:24 UTC, Glitch458 requested changes
Пара мелких правок. 
Я увидел контейнер 1205рх. Вроде всё хорошо) Не понял где проблема

2021-07-06 19:24 UTC, Glitch458 commented on src/sass/components/_about.scss
> +  @media screen and (mon-wodth: 1366px) {
Очепятка

2021-07-06 19:24 UTC, Glitch458 commented on src/sass/components/_about.scss
> + font-size: 14px;
Меняется на точках перелома: 768рх - 12рх. 1366 - 16рх

2021-07-07 03:27 UTC, OleksandrKudriavtsev commented on src/sass/components/_about.scss
> +  @media screen and (mon-wodth: 1366px) {
Исправил

2021-07-07 03:28 UTC, OleksandrKudriavtsev commented on src/sass/components/_about.scss
> + font-size: 14px;
Исправил

2021-07-07 08:27 UTC, Glitch458 approved these changes

2021-07-07 08:32 UTC, merged