_benefits-min-vers
YaroslavKnysh/team_project_13_37 pull request #47
Opened 2021-07-07 20:47 UTC by OleksandrKudriavtsev

Все плохо)) Комментарии в коде

2021-07-07 23:56 UTC, Glitch458 requested changes
Десктоп выглядит хорошо) Остальное постарался поправить как смог. Всё криво поехало через маржины между лишками. На планшетной версии в секции benefits сам макет кривой. Маржины между лишками разные. Я их не трогал, двигал секцию с тем что есть. Пересмотри использование max-width. Много лишнего приходится писать)

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_benefits.scss
> +      margin-bottom: 20px;
36px по макету

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_about.scss
> +    margin-top: 200px;
270 по макету. В связке с маржином между лишками и поправкой транслейта (комменты ниже), мобилка станет как надо

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_benefits.scss
> +  transform: translateY(-77%);
транслейт -66% (поправка на маржин между li)

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_benefits.scss
> +  @media screen and  (max-width: 479px) {
Можно обойтись без max-width. Просто на 480 перебить нужные значения. и width: 100vw не придется еще раз писать

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_benefits.scss
> +  @media screen and (min-width: 480px) and (max-width: 767px) {
тоже самое. без max-width

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_benefits.scss
> +  width: 100vw;
Оставить только этот. Остальные удалить

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_benefits.scss
> +  transform: translateY(-94%);
-75% Поправка.

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_about.scss
> +    margin-top: 80px;
Вот тут как раз 200рх отлично станет.

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_about.scss
> +    margin-top: 200px;
Также убери медиа правило) стараемся не юзать max-width. мы этот маржин просто перебьем следующим медиа правилом

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_about.scss
> +    margin-top: 280px;
302 по макету

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_about.scss
> +  @media screen and (min-width: 768px) {
Если уже выше указал max-width, то сбрасывать маржин этим медиа правилом уже не нужно. Свыше 767рх маржин вернет свое значение по-умолчанию - 0

2021-07-07 23:56 UTC, Glitch458 commented on src/sass/components/_benefits.scss
> +  transform: translateY(-33%);
-43% с поправкой

2021-07-08 00:38 UTC, OleksandrKudriavtsev commented on src/sass/components/_about.scss
> +    margin-top: 200px;
++

2021-07-08 00:41 UTC, OleksandrKudriavtsev commented on src/sass/components/_benefits.scss
> +      margin-bottom: 20px;
Нашел на десктопе 32рх, поправил

2021-07-08 00:42 UTC, OleksandrKudriavtsev commented on src/sass/components/_benefits.scss
> +  transform: translateY(-77%);
++

2021-07-08 00:46 UTC, OleksandrKudriavtsev commented on src/sass/components/_benefits.scss
> +  @media screen and  (max-width: 479px) {
++

2021-07-08 00:47 UTC, OleksandrKudriavtsev commented on src/sass/components/_benefits.scss
> +  @media screen and (min-width: 480px) and (max-width: 767px) {
++

2021-07-08 00:47 UTC, OleksandrKudriavtsev commented on src/sass/components/_benefits.scss
> +  width: 100vw;
++

2021-07-08 00:48 UTC, OleksandrKudriavtsev commented on src/sass/components/_benefits.scss
> +  transform: translateY(-94%);
++

2021-07-08 00:48 UTC, OleksandrKudriavtsev commented on src/sass/components/_about.scss
> +    margin-top: 80px;
++

2021-07-08 00:49 UTC, OleksandrKudriavtsev commented on src/sass/components/_about.scss
> +    margin-top: 280px;
++

2021-07-08 00:50 UTC, OleksandrKudriavtsev commented on src/sass/components/_about.scss
> +  @media screen and (min-width: 768px) {
++

2021-07-08 00:50 UTC, OleksandrKudriavtsev commented on src/sass/components/_benefits.scss
> +  transform: translateY(-33%);
++

2021-07-08 07:03 UTC, merged